-- MySQL Script generated by MySQL Workbench
-- Fri Mar 30 21:01:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Legit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Legit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Legit` DEFAULT CHARACTER SET utf8 ;
USE `Legit` ;

-- -----------------------------------------------------
-- Table `Legit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `registrationDate` DATE NOT NULL,
  `lastLogin` DATETIME NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Legit`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `total_cost` DECIMAL(8,2) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `idUser_idx` (`id_user` ASC),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `Legit`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `Legit`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(7,2) NOT NULL,
  `model` VARCHAR(150) NOT NULL,
  `rating` DECIMAL(3,2) NULL,
  `description` VARCHAR(3000) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Legit`.`user_has_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`user_has_favorites` (
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  INDEX `idProduct_idx` (`id_product` ASC),
  INDEX `idUser_idx` (`id_user` ASC),
  PRIMARY KEY (`id_product`, `id_user`),
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `Legit`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `Legit`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `Legit`.`order_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`order_has_products` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `product_quantity` INT NOT NULL,
  INDEX `id_order_idx` (`id_order` ASC, `id_product` ASC),
  PRIMARY KEY (`id_order`, `id_product`),
  INDEX `id_product_idx` (`id_product` ASC),
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `Legit`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `Legit`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Legit` ;

-- -----------------------------------------------------
-- Placeholder table for view `Legit`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Legit`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Legit`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Legit`.`view1`;
USE `Legit`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
